name: ShareControl
main: ru.h1karo.sharecontrol.ShareControl
version: '${project.version}-${project.build}'
authors:
  - h1karo
softdepend: [Essentials, WorldEdit]
description: Control mode of creativity.
website: http://dev.bukkit.org/bukkit-plugins/sharecontrol/
api-version: '1.15'
commands:
   sharecontrol:
      description: Principal command of plugin
      permission: sharecontrol.commands.*
      usage: /sharecontrol
      aliases: [sc]