name: ShareControl
main: ${mainClass}
version: '${project.version.full}'
authors:
  - h1karo
description: Manage the cross-mode play
website: https://github.com/h1karo/sharecontrol
api-version: 1.19
commands:
   sharecontrol:
      description: Principal command of plugin
      permission: sharecontrol.commands.*
      usage: /sharecontrol
      aliases: [sc]