name: ShareControl
main: ${mainClass}
version: '${project.version.full}'
authors:
  - h1karo
description: Manage the cross-mode play
website: http://dev.bukkit.org/bukkit-plugins/sharecontrol/
commands:
   sharecontrol:
      description: Principal command of plugin
      permission: sharecontrol.commands.*
      usage: /sharecontrol
      aliases: [sc]